// engine.go defines the Engine type and its public entry points Run and RunDocument.
// Pipeline stages are implemented in parse.go, overlays.go, pipeline.go, and helpers.go.
// Output formatting is in format.go.

package engine

import (
	"fmt"
	"os"
	"strings"
)

// Config carries runtime options for a single tractl run invocation.
type Config struct {
	// WorkflowFile is the path to the workflow file.
	WorkflowFile string
	// EnvName is the active environment name (empty = none).
	EnvName string
	// OverlayFiles are paths to overlay files, applied in order.
	OverlayFiles []string
	// TraceID is a unique identifier for this execution.
	// Generated by the engine when empty.
	TraceID string
	// Quiet suppresses all [engine]/[dag] log output. Set when output format is
	// machine-readable (e.g. JSON) so logs don't pollute stdout.
	Quiet bool
	// Verbose includes HTTP response status, headers, and body in every StepOutcome.
	// Applies to both text and JSON output.
	Verbose bool

	// MaxConcurrentScripts caps the number of goja.Runtime instances that may
	// execute simultaneously across all workflows and steps in one Run() call.
	// Scripts beyond this cap block until a slot is available, respecting ctx
	// cancellation. If ≤ 0, defaults to runtime.NumCPU().
	MaxConcurrentScripts int

	// Dependency overrides for testing. If nil, pipeline.go uses default concrete types.
	Planner      Planner
	Compiler     Compiler
	Evaluator    Evaluator
	ScriptRunner ScriptRunner
}

// DocumentConfig carries runtime options for an in-memory workflow document.
// It is used by surfaces that receive document text directly, such as the
// browser WASM bridge, while preserving the same engine pipeline as Run.
type DocumentConfig struct {
	// Document is the workflow document content.
	Document string
	// Format is the document format: yaml, yml, json, or toon.
	Format string
	// SourceRef is recorded in parser metadata for diagnostics.
	SourceRef string
	// EnvName is the active environment name (empty = none).
	EnvName string
	// TraceID is a unique identifier for this execution.
	// Generated by the engine when empty.
	TraceID string
	// Quiet suppresses all [engine]/[dag] log output.
	Quiet bool
	// Verbose includes HTTP response status, headers, and body in every StepOutcome.
	Verbose bool
	// MaxConcurrentScripts caps simultaneous script execution.
	MaxConcurrentScripts int
}

// Engine wires all internal phases together.
type Engine struct{}

// New returns a new Engine.
func New() *Engine { return &Engine{} }

// Run executes the full file-based pipeline for the given config and returns a RunResult.
// Run never panics; all errors are captured inside RunResult.
func (e *Engine) Run(cfg Config) *RunResult {
	// ── STAGE 1: detect format + parse ───────────────────────────────────────

	src, err := os.ReadFile(cfg.WorkflowFile)
	if err != nil {
		return &RunResult{ParseError: fmt.Sprintf("cannot read workflow file %q: %v", cfg.WorkflowFile, err)}
	}

	s, parseErr := parseByExtension(src, cfg.WorkflowFile)
	if parseErr != nil {
		return &RunResult{ParseError: parseErr.Error()}
	}

	// ── STAGE 2: apply overlays ───────────────────────────────────────────────

	if len(cfg.OverlayFiles) > 0 {
		s, err = applyOverlays(s, cfg.OverlayFiles)
		if err != nil {
			return &RunResult{ParseError: err.Error()}
		}
	}

	return e.runSpec(s, cfg)
}

// RunDocument executes the full pipeline for an in-memory workflow document.
// It shares all post-parse stages with Run and never panics; all errors are
// captured inside RunResult.
func (e *Engine) RunDocument(cfg DocumentConfig) *RunResult {
	sourceRef := cfg.SourceRef
	if strings.TrimSpace(sourceRef) == "" {
		sourceRef = fallbackSourceRef
	}

	s, parseErr := ParseByFormat([]byte(cfg.Document), cfg.Format, sourceRef)
	if parseErr != nil {
		return &RunResult{ParseError: parseErr.Error()}
	}

	return e.runSpec(s, Config{
		EnvName:              cfg.EnvName,
		TraceID:              cfg.TraceID,
		Quiet:                cfg.Quiet,
		Verbose:              cfg.Verbose,
		MaxConcurrentScripts: cfg.MaxConcurrentScripts,
	})
}
